---
- name: Converge
  hosts: all
  collections:
   - matthewcosgrove.tools_vm
  vars:
   gitlab_username: "{{ lookup('env', 'GITLAB_USERNAME') }}"
  tasks:
    - name: "Include ubuntu_user"
      include_role:
        name: "ubuntu_user"
    - name: "Include vim"
      include_role:
        name: "vim"
    - name: "Include vim_plugins"
      include_role:
        name: "vim_plugins"
    - name: "Include bucc_tools"
      include_role:
        name: "bucc_tools"
    - name: "Include hashicorp_tools"
      include_role:
        name: "hashicorp_tools"
